#Sweeney, Harrison and Vander Linden 2021. 
#Assessing anthropogenic influence on fire history during the Holocene in the Iberian Peninsula
# ---------------------------------------------------------

#There are seven seperate scripts associated with this research:
# 1. data_import.R 
# 2. charcoal_analysis.R 
# 3. radiocarbon_analysis.R (this script)
# 4. correlation_analysis.R
# 5. SEA_analysis.R
# 6. neolithic_analysis.R
# 7. maps.R

# ---------------------------------------------------------


# Archaeological radiocarbon population data analysis
# ---------------------------------------------------------
# ---------------------------------------------------------
# This script sets up the radiocarbon data for subsequent 
# relationship analysis with the charcoal data in 
# fire_human_relationship_analysis.R. To generate the data
# used in this script, the data_import.R script should be
# run first


# Script elements
# ---------------------------------------------------------
# 1. Packages and paths
# 2. Data import
# 3. Calibration, SPDs, SPD plots and data histogram
# 4. Neolithic surface
# 5. Changepoint analysis
# 6. Save data for correlation analysis


# 1. Packages
# ---------------------------------------------------------
# ---------------------------------------------------------

# Install
# ---------------------------------------------------------
# install.packages("c14bazAAR", repos = c(ropensci = "https://ropensci.r-universe.dev"))
# install.packages("changepoint")
# install.packages("fable")
# install.packages("fabletools")
# install.packages("feasts")
# install.packages("ggpubr")
# install.packages("gridExtra")
# install.packages("gstat")
# install.packages("locfit")
# install.packages("maps")
# install.packages("naniar")
# install.packages("rnaturalearth")
# install.packages("raster")
# install.packages("rcarbon")
# install.packages("rgdal")
# install.packages("rgeos")
# install.packages("rio")
# install.packages("sf")
# install.packages("spatstat")
# install.packages("tidyverse")
# install.packages("tseries")
# install.packages("zoo")


# Library
# ---------------------------------------------------------
library(c14bazAAr)
library(changepoint)
library(fable)
library(fabletools)
library(feasts)
library(ggpubr)
library(gridExtra)
library(gstat)
library(locfit)
library(maps)
library(naniar)
library(rnaturalearth)
library(raster)
library(rcarbon)
library(rgdal)
library(rgeos)
library(rio)
library(sf)
library(spatstat)
library(tidyverse)
library(tseries)
library(zoo)


# Paths
# ---------------------------------------------------------
# The script currently runs with the following sub-folders:
# /data: any data that is used for the analysis
# /figs:  figures outputted from the analysis
#   /rpd/cor            : correlation plots
#   /rpd/maps           : maps
#   /pop/SPD/           : SPD plots
#   /pop/SPD/Neo/Kriging: Neolithic surface plots
#   /pop/SPD/Neo/Vario  : Neolithic variogram plots
#   /rpd/rpd            : charcoal composite plots
#   /rpd/neo_rpd        : Neolithic analysis plots
#   /rpd/sea_rpd        : SEA analysis plots
# /other_output         : other types of output
#    /rpd               : intermediate output
#       /rpd_debug      : location for debug files (charcoal)
#       /rpd_influx     : generated influx csvs (charcoal)
#       /z_trans_rpd    : transformed csvs (charcoal)
#       /stats_rpd      : statistics relating to records (charcoal)
#    /pop               : intermediate outpu


# If the folders have not yet been created, the following code
# will generate these from the working directory, with the exception of
# the code file, where this and the other 6 scripts should be saved:

# dir.create("data")
# dir.create("figs")
# dir.create("figs/cor")
# dir.create("figs/maps")
# dir.create("figs/pop")
# dir.create("figs/pop/SPD")
# dir.create("figs/pop/Neo")
# dir.create("figs/pop/Neo/Vario")
# dir.create("figs/pop/Neo/Kriging")
# dir.create("figs/rpd")
# dir.create("figs/sea_rpd")
# dir.create("figs/neo_rpd")
# dir.create("figs/sea_rpd")
# dir.create("other_output")
# dir.create("other_output/pop")
# dir.create("other_output/rpd")
# dir.create("other_output/rpd/rpd_debug")
# dir.create("other_output/rpd/rpd_influx")
# dir.create("other_output/rpd/stats_rpd")
# dir.create("other_output/rpd/z_trans_rpd")

# ---------------------------------------------------------



# 2. Population data to import
# ---------------------------------------------------------
# ---------------------------------------------------------

# Import dataset
# ---------------------------------------------------------
radiocarbon_data <- rio::import("other_output/pop/radiocarbon_data.csv") #This is the radiocarbon data used for publication, generated by data_import.R



# 3. Generate and plot SPD
# ---------------------------------------------------------
# ---------------------------------------------------------

# Calibrate data and generate spds
# ---------------------------------------------------------

# Calibration of radiocarbon data
calibrated_data <- rcarbon::calibrate(x = radiocarbon_data$c14_age, #Data calibration
                                      errors = radiocarbon_data$c14_std, 
                                      normalised = FALSE, 
                                      ncores = 4, #Set the number of cores available for analysis
                                      calCurves = radiocarbon_data$calibration_curve,
                                      resOffsets = radiocarbon_data$reservoir_offset, 
                                      resErrors = radiocarbon_data$reservoir_std)


#Site binning
c14_bins <- rcarbon::binPrep(sites = radiocarbon_data$site_id, ages = radiocarbon_data$c14_age, h = 100) #100 year bins

#Generate SPD
spd <- rcarbon::spd(calibrated_data, timeRange = c(10000, 3500), bins = c14_bins) #Run SPD for data range
spd_rm200 <- rcarbon::spd(calibrated_data, timeRange = c(10000, 3500), bins = c14_bins, runm = 200) #SPD with 200 year running mean


# Generate NULL models
# ---------------------------------------------------------
nsim = 1000 #Number of simulations to run
set.seed(42)
ncores = 8 #Enter number of cores available

# Exponential fit
null_exp <- rcarbon::modelTest(calibrated_data, #Run model test using exponential model
                               errors = radiocarbon_data$c14_std, 
                               bins = c14_bins, 
                               nsim = nsim, 
                               timeRange = c(10000,3500), 
                               model = "exponential", 
                               runm = 200, 
                               ncores = ncores) 

summary(null_exp) #Summary output of Model test with exponential model
summary(null_exp, type = "roc") #Summary output of Model test with exponential model, rate of change

# Logistic fit
logFit<- nls(PrDens ~ SSlogis(calBP, Asym, xmid, scale), #Set up step 1 to generate logistic fit
                       data = spd_rm200$grid,
                       control = nls.control(maxiter = 200),
                       start = list(Asym = 1.25, xmid = 4700, scale = -100))


# Generate a data frame containing the fitted values
logFitDens <-  data.frame(calBP = spd_rm200$grid$calBP, #Set up step 2 to generate logistic fit
                          PrDens = SSlogis(input = spd$grid$calBP,
                                           Asym = coefficients(logFit)[1],
                                           xmid = coefficients(logFit)[2],
                                           scal = coefficients(logFit)[3]))

# Use the modelTest function (returning the raw simulation output - see below)
null_logistic <- rcarbon::modelTest(calibrated_data, #Run model test using logistic model
                                    errors = radiocarbon_data$c14_std,
                                    bins = c14_bins, nsim = nsim,
                                    timeRange = c(10000,3500),
                                    model = "custom",
                                    predgrid = logFitDens,
                                    runm = 200,
                                    raw = TRUE,
                                    ncores = ncores)

summary(null_logistic) #Summary output of Model test with logistic model
summary(null_logistic, type = "roc") #Summary output of Model test with logistic model, rate of change



# Plots of SPDs
# ---------------------------------------------------------

#SPD
plot_spd <- rgeos::plot(spd, runm = 200) #To check plot of SPD with 200 year running mean

#Exponential null
pdf("figs/pop/SPD/SPD_200rm_exp_norm_and_ROC.pdf", height = 5, width = 6.27, pointsize = 9, family = "Times")
par(mfrow = c(2,1), mar = c(3, 4, 1, 1), mgp = c(2.4, 1, 0))
plot_null <- rgeos::plot(null_exp, xlim = c(10000, 3500), ann = FALSE)
title(ylab = "Summed Probability", cex.lab = 1.2)
text(x = 9750, y = 1.75, "A", font = 2)
grid()
par(mar = c(4, 4, 0, 1), mgp = c(2.4, 1, 0))
plot_null <- rgeos::plot(null_exp, type = "roc", xlim = c(10000, 3500), ann = FALSE)
title(ylab = "Summed Probability", cex.lab = 1.2)
title(xlab = "Years cal. BP", cex.lab = 1.2)
text(x = 9750, y = 0.0125, "B", font = 2)
grid()
dev.off()

#Exponential and logistic null
pdf("figs/pop/SPD/SPD_200rm_NULL_explog_norm_and_ROC.pdf", height = 5, width = 6.27, pointsize = 9, family = "Times")
par(mfrow = c(2,2), mar = c(3, 4, 1, 1), mgp = c(2.4, 1, 0))
plot_null <- rgeos::plot(null_exp, xlim = c(10000, 3500), ann = FALSE)
title(ylab = "Summed Probability", cex.lab = 1.2)
text(x = 9750, y = 1.75, "A", font = 2)
grid()
par(mar = c(3, 4, 1, 1), mgp = c(2.4, 1, 0))
plot_null <- rgeos::plot(null_exp, type = "roc", xlim = c(10000, 3500), ann = FALSE)
title(ylab = "Summed Probability", cex.lab = 1.2)
text(x = 9750, y = 0.0125, "B", font = 2)
grid()
par(mar = c(4, 4, 0, 1), mgp = c(2.4, 1, 0))
plot_null <- rgeos::plot(null_logistic, xlim = c(10000, 3500), ann = FALSE)
title(ylab = "Summed Probability", cex.lab = 1.2)
title(xlab = "Years cal. BP", cex.lab = 1.2)
text(x = 9750, y = 1.25, "C", font = 2)
grid()
par(mar = c(4, 4, 0, 1), mgp = c(2.4, 1, 0))
plot_null <- rgeos::plot(null_logistic, type = "roc", xlim = c(10000, 3500), ann = FALSE)
title(ylab = "Summed Probability", cex.lab = 1.2)
title(xlab = "Years cal. BP", cex.lab = 1.2)
text(x = 9750, y = 0.016, "D", font = 2)
grid()
dev.off()


# Histogram plot
# ---------------------------------------------------------

# Extract and add calibrated dates
radiocarbon_caldates <- rcarbon::medCal(calibrated_data) %>%  #Extract the calibrated dates
  tibble::as_tibble() %>% 
  dplyr::mutate(date_id = calibrated_data$metadata$DateID)

radiocarbon_data_cal <- radiocarbon_data %>% #Transform radiocarbon to sf object for plotting
  dplyr::mutate(median_caldates = radiocarbon_caldates$value)  #Add calibrated dates
  
rio::export(radiocarbon_data_cal, "./other_output/pop/radiocarbon_data_cal.csv") #Export for neolithic_analysis.R and maps.R

radiocarbon_data_sf <- radiocarbon_data %>% #Transform radiocarbon to sf object for plotting
  dplyr::mutate(median_caldates = radiocarbon_caldates$value) %>% #Add calibrated dates
  sf::st_as_sf(coords = c("longitude", "latitude"), crs = 4258, agr = "constant") %>% 
  sf::st_transform(crs = 25830) #Flat projection


# Histograms of calibrated data
ggplot2::ggplot(data = dplyr::filter(radiocarbon_data_sf, dplyr::between(median_caldates, 3500, 10000)), mapping = aes(median_caldates)) +
  geom_histogram(binwidth = 100) +
  labs(x = "Years cal. BP", y = "Count") +
  theme(plot.margin = unit(c(4,4,1,1), "mm"), panel.background = element_rect(fill = "white", color = "black"), panel.grid = element_line(color = "gray", linetype = 3)) +
  theme(text = element_text(family = "Times", size = 12))+
  scale_x_reverse(breaks = scales::pretty_breaks(n = 10)) 
  ggsave("figs/pop/Iberia_caldata_by_year_hist.pdf", height = 8, width = 15, units = "cm")




# 4. Neolithic analysis
# ---------------------------------------------------------
# ---------------------------------------------------------


# Generate map window
# ---------------------------------------------------------
iberia_map <- maps::map("world", c("Spain(?!:)", "Portugal", "Andorra"), fill = T, resolution = 0) #Download map of Iberia
iberia_map <- sf::st_as_sf(iberia_map) #Convert to sf
iberia_map_25830 <- sf::st_transform(iberia_map, crs = 25830) #Change the crs to flat projection
iberia_owin_25830 <- spatstat.geom::as.owin(iberia_map_25830) #Generate owin window
iberia_owin_25830_exp <- spatstat.random::expand.owin(iberia_owin_25830, distance = 2000) #Expand owin to try and ensure that samples are not excluded due to coord inaccuracies 
iberia_map_exp_25830 <-  sf::st_as_sf(iberia_owin_25830_exp) #Convert back to sf
sf::st_crs(iberia_map_exp_25830) <- 25830 #Set crs
iberia_map_exp <- sf::st_transform(iberia_map_exp_25830, crs = 4258) #Change crs back to ellipsoid for raster



# Generate Neolithic surface
# ---------------------------------------------------------

radiocarbon_data_xy <- sf::st_coordinates(radiocarbon_data_sf) %>% #Extract coordinate information
  dplyr::as_tibble()

neo_data <- radiocarbon_data_sf %>% #Set up Neolithic date SS
  dplyr::mutate(x = radiocarbon_data_xy$X, y = radiocarbon_data_xy$Y) %>% 
  dplyr::as_tibble() %>% 
  dplyr::mutate(date_id = radiocarbon_caldates$date_id) %>% 
  dplyr::select(x, y, median_caldates, c14_age: date_id)  %>% 
  dplyr::filter(neolithic_tag ==  "Neolithic") %>% #Only select dates that have Neolithic tag
  dplyr::arrange(median_caldates) %>% 
  dplyr::filter(between(median_caldates, 0, 7600)) #Allowable dates for first date of Neolithic

buff <- 50000 #Set buffer size

neo_data_xy <- neo_data %>% #Generate x y of Neolithic dates
  dplyr::select(x, y) 

iberia_map_exp_25830_rast_small <- raster::raster(iberia_map_exp_25830, res = c(1000, 1000)) #Change interpolation resolution to 1km2

neo_data_rast <- raster::rasterize(neo_data_xy, iberia_map_exp_25830_rast_small, fun = max, field = neo_data$median_caldates)  #Place xy neo into raster with oldest neo date, 1km2

extract_buffer <- raster::extract(neo_data_rast, neo_data_xy, buffer = buff, fun = max, df = T) #Establish buffer around each point to show max in buffer

neo_data_xyz <- neo_data %>% 
  dplyr::mutate(buffer_extract = extract_buffer$layer) %>% #For each sample, establish oldest date in its own buffer
  dplyr::mutate(test = dplyr::if_else(buffer_extract == median_caldates, "max", "not_max"))   %>%  
  dplyr::filter(test == "max") %>%  #Only select samples that are the oldest in its own buffer
  dplyr::select(x, y, median_caldates) %>% 
  dplyr::rename(layer = median_caldates) %>% 
  sf::st_as_sf(coords = c("x", "y"), crs = 25830, agr = "constant") %>%  
  sf::as_Spatial()


# Variogram
vario <- gstat::variogram(layer~1, neo_data_xyz) #Generate variogram based on filtered buffer points

# Variogram models
vario_fit <- gstat::fit.variogram(vario, gstat::vgm(c("Exp")), fit.kappa = T) #Fit variogram
vario_fit_ste <- gstat::fit.variogram(vario, gstat::vgm(c("Ste")), fit.kappa = T) #Fit variogram best
vario_fit_mat <- gstat::fit.variogram(vario, gstat::vgm(c("Mat")), fit.kappa = T) #Fit variogram 2nd best
vario_fit_sph <- gstat::fit.variogram(vario, gstat::vgm(c("Sph")), fit.kappa = T) #Fit variogram 3rd best

vario_sserr <- attr(vario_fit, "SSErr")
vario_sserr_ste <- attr(vario_fit_ste, "SSErr")
vario_sserr_mat <- attr(vario_fit_mat, "SSErr")
vario_sserr_sph <- attr(vario_fit_sph, "SSErr")

plot(vario, vario_fit) #Show variogram and fit

#Kriging
krige_neo <- gstat::krige(layer~1, neo_data_xyz, as(iberia_map_exp_25830_rast_small, "SpatialPixels"), model=vario_fit) #Perform kriging based on model and interpolation raster
krige_neo_raster <- raster::raster(krige_neo) %>%  #Generate raster
  raster::mask(iberia_map_exp_25830)

krige_neo_ste <- gstat::krige(layer~1, neo_data_xyz, as(iberia_map_exp_25830_rast_small, "SpatialPixels"), model=vario_fit_ste) #Perform kriging based on model and interpolation raster
krige_neo_raster_ste <- raster::raster(krige_neo_ste) %>%  #Generate raster
  raster::mask(iberia_map_exp_25830)

krige_neo_mat <- gstat::krige(layer~1, neo_data_xyz, as(iberia_map_exp_25830_rast_small, "SpatialPixels"), model=vario_fit_mat) #Perform kriging based on model and interpolation raster
krige_neo_raster_mat <- raster::raster(krige_neo_mat) %>%  #Generate raster
  raster::mask(iberia_map_exp_25830)

krige_neo_sph <- gstat::krige(layer~1, neo_data_xyz, as(iberia_map_exp_25830_rast_small, "SpatialPixels"), model=vario_fit_sph) #Perform kriging based on model and interpolation raster
krige_neo_raster_sph <- raster::raster(krige_neo_sph) %>%  #Generate raster
  raster::mask(iberia_map_exp_25830)

#Max and min values for kriging
max_krige_neo_raster <- max(krige_neo_raster@data@values, na.rm = T) 
min_krige_neo_raster <- min(krige_neo_raster@data@values, na.rm = T)

max_krige_neo_raster_ste <- max(krige_neo_raster_ste@data@values, na.rm = T)
min_krige_neo_raster_ste <- min(krige_neo_raster_ste@data@values, na.rm = T)

max_krige_neo_raster_mat <- max(krige_neo_raster_mat@data@values, na.rm = T)
min_krige_neo_raster_mat <- min(krige_neo_raster_mat@data@values, na.rm = T)

max_krige_neo_raster_sph <- max(krige_neo_raster_sph@data@values, na.rm = T)
min_krige_neo_raster_sph <- min(krige_neo_raster_sph@data@values, na.rm = T)

#Variogram fit plotting
vario_preds <- gstat::variogramLine(vario_fit, maxdist = max(vario$dist)) %>% 
  dplyr::mutate(Model = paste0("Exponential", ": ", round(vario_sserr))) #Add fit standard error
vario_preds_ste <- gstat::variogramLine(vario_fit_ste, maxdist = max(vario$dist)) %>% 
  dplyr::mutate(Model = paste0("Stein Matern", ": ", round(vario_sserr_ste))) #Add fit standard error
vario_preds_mat <- gstat::variogramLine(vario_fit_mat, maxdist = max(vario$dist)) %>% 
  dplyr::mutate(Model = paste0("Matern", ": ", round(vario_sserr_mat))) #Add fit standard error
vario_preds_sph <- gstat::variogramLine(vario_fit_sph, maxdist = max(vario$dist)) %>% 
  dplyr::mutate(Model = paste0("Spherical", ": ", round(vario_sserr_sph))) #Add fit standard error

vario_models <- vario_preds %>% #Combine model outputs for plotting
  rbind(vario_preds_ste, vario_preds_mat, vario_preds_sph)

ggplot2::ggplot(data = vario, mapping = aes(x = dist, y = gamma)) +
  geom_point()+
  geom_line(data = vario_models, aes(x = dist, y = gamma, color = Model))+
  ggplot2::labs(x = "Distance", y = "Semivariance", color = "Model and fit standard error")+
  theme(plot.margin = unit(c(4,4,1,1), "mm"), panel.background = element_rect(fill = "white", color = "black"), panel.grid = element_line(color = "gray", linetype = 3)) +
  theme(text = element_text(family = "Times", size = 12))
  ggplot2::ggsave("./figs/pop/Neo/Vario/vario.pdf", height = 8, width = 15, units = "cm")


raster::writeRaster(krige_neo_raster, "other_output/pop/kriging_neoloithic.grd", overwrite=TRUE) #To be used in neolithic_analysis.R

#Plot kriging
lon_lat_krige_neo_raster <- raster::projectRaster(krige_neo_raster, crs = 4258) #Change projection to spherical
lon_lat_krige_neo_raster_ste <- raster::projectRaster(krige_neo_raster_ste, crs = 4258) #Change projection to spherical
lon_lat_krige_neo_raster_mat <- raster::projectRaster(krige_neo_raster_mat, crs = 4258) #Change projection to spherical
lon_lat_krige_neo_raster_sph <- raster::projectRaster(krige_neo_raster_sph, crs = 4258) #Change projection to spherical

pdf("figs/pop/Neo/Kriging/lon_lat_krige_neo_raster.pdf", height = 3.15, width = 4.5, pointsize = 9)
par(mar = c(2, 2, 1, 1))
raster::plot(lon_lat_krige_neo_raster, col = hcl.colors(20, "Viridis"), colNA = "aliceblue")
dev.off()

pdf("figs/pop/Neo/Kriging/lon_lat_krige_neo_raster_ste.pdf", height = 3.15, width = 4.5, pointsize = 9)
par(mar = c(2, 2, 1, 1))
raster::plot(lon_lat_krige_neo_raster_ste, col = hcl.colors(20, "Viridis"), colNA = "aliceblue")
dev.off()

pdf("figs/pop/Neo/Kriging/lon_lat_krige_neo_raster_mat.pdf", height = 3.15, width = 4.5, pointsize = 9)
par(mar = c(2, 2, 1, 1))
raster::plot(lon_lat_krige_neo_raster_mat, col = hcl.colors(20, "Viridis"), colNA = "aliceblue")
dev.off()

pdf("figs/pop/Neo/Kriging/lon_lat_krige_neo_raster_sph.pdf", height = 3.15, width = 4.5, pointsize = 9)
par(mar = c(2, 2, 1, 1))
raster::plot(lon_lat_krige_neo_raster_sph, col = hcl.colors(20, "Viridis"), colNA = "aliceblue")
dev.off()




# 5. Changepoint analysis
# ---------------------------------------------------------
# ---------------------------------------------------------
change_spd <- spd_rm200$grid$PrDens #Select probability densities
spd_cp_binseg_mean <- changepoint::cpt.mean(change_spd, method = "BinSeg", "MBIC") #Run changepoint analysis on mean values

png("figs/pop/SPD/SPD_200_coords_not_normal_binned_changpoint_binseg.png", height = 30, width = 30, units = "cm", res = 150, pointsize = 24)
plot(spd_cp_binseg_mean, cpt.col = "red", xaxt="n", ylab = "", xlab = "")
axis(1, at = c(0, 2000, 4000, 6000), labels = c(10000, 8000, 6000, 4000)) #Necessary as changepoint works from low to high
title(xlab = list("Years cal. BP", cex = 1.1), ylab = list("Summed Probability", cex = 1.1))
dev.off()

first_spd_changepoint <- 10000 - spd_cp_binseg_mean@cpts[1] #First changepoint location. 10k minus because of BP dates
second_spd_changepoint <- 10000 - spd_cp_binseg_mean@cpts[2] #Second changepoint location. 10k minus because of BP dates



# 6. Save data for correlation analysis
# ---------------------------------------------------------
# ---------------------------------------------------------

spd_data <- dplyr::tibble(age = spd$grid$calBP, spd = spd$grid$PrDens)
rio::export(spd_data, "./other_output/pop/spd_data.csv") #To be used in correlation analysis
spd_data_sm <- dplyr::tibble(age = spd_rm200$grid$calBP, spd = spd_rm200$grid$PrDens)
rio::export(spd_data_sm, "./other_output/pop/spd_data_sm.csv") #To be used in correlation analysis



